{% set name = "darts" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/darts-{{ version }}.tar.gz
  sha256: 54f3d22069a4d3246926d77f941a6def3afc0f8837ea38b8483528d4ffcad675

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - fbprophet ==0.6
    - holidays ==0.10.2
    - ipython ==7.15.0
    - matplotlib-base ==3.2.2
    - numpy ==1.19.0
    - pandas ==1.1.0
    - pmdarima ==1.6.1
    - python >=3.6
    - scikit-learn ==0.23.2
    - scipy ==1.5.0
    - statsmodels ==0.11.1
    - tensorboard ==2.4.0
    - torch ==1.7.1
    - tqdm ==4.46.1

test:
  imports:
    - darts
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://unit8co.github.io/darts/
  summary: A python library for easy manipulation and forecasting of time series.
  license: Apache-2.0
  license_file: PLEASE_ADD_LICENSE_FILE

extra:
  recipe-maintainers:
    - unit8
